// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: redis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RedisService_SetUUID_FullMethodName                 = "/proto.RedisService/SetUUID"
	RedisService_RemoveUUID_FullMethodName              = "/proto.RedisService/RemoveUUID"
	RedisService_CheckExistedUserSession_FullMethodName = "/proto.RedisService/CheckExistedUserSession"
)

// RedisServiceClient is the client API for RedisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedisServiceClient interface {
	SetUUID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Response, error)
	RemoveUUID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Response, error)
	CheckExistedUserSession(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*LoginResponse, error)
}

type redisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedisServiceClient(cc grpc.ClientConnInterface) RedisServiceClient {
	return &redisServiceClient{cc}
}

func (c *redisServiceClient) SetUUID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, RedisService_SetUUID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) RemoveUUID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, RedisService_RemoveUUID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) CheckExistedUserSession(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, RedisService_CheckExistedUserSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedisServiceServer is the server API for RedisService service.
// All implementations must embed UnimplementedRedisServiceServer
// for forward compatibility
type RedisServiceServer interface {
	SetUUID(context.Context, *UserID) (*Response, error)
	RemoveUUID(context.Context, *UserID) (*Response, error)
	CheckExistedUserSession(context.Context, *UserID) (*LoginResponse, error)
	mustEmbedUnimplementedRedisServiceServer()
}

// UnimplementedRedisServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRedisServiceServer struct {
}

func (UnimplementedRedisServiceServer) SetUUID(context.Context, *UserID) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUUID not implemented")
}
func (UnimplementedRedisServiceServer) RemoveUUID(context.Context, *UserID) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUUID not implemented")
}
func (UnimplementedRedisServiceServer) CheckExistedUserSession(context.Context, *UserID) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckExistedUserSession not implemented")
}
func (UnimplementedRedisServiceServer) mustEmbedUnimplementedRedisServiceServer() {}

// UnsafeRedisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedisServiceServer will
// result in compilation errors.
type UnsafeRedisServiceServer interface {
	mustEmbedUnimplementedRedisServiceServer()
}

func RegisterRedisServiceServer(s grpc.ServiceRegistrar, srv RedisServiceServer) {
	s.RegisterService(&RedisService_ServiceDesc, srv)
}

func _RedisService_SetUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).SetUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_SetUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).SetUUID(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_RemoveUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).RemoveUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_RemoveUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).RemoveUUID(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_CheckExistedUserSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).CheckExistedUserSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_CheckExistedUserSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).CheckExistedUserSession(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

// RedisService_ServiceDesc is the grpc.ServiceDesc for RedisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RedisService",
	HandlerType: (*RedisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUUID",
			Handler:    _RedisService_SetUUID_Handler,
		},
		{
			MethodName: "RemoveUUID",
			Handler:    _RedisService_RemoveUUID_Handler,
		},
		{
			MethodName: "CheckExistedUserSession",
			Handler:    _RedisService_CheckExistedUserSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redis.proto",
}
