version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./backend:/app
      - ./backend/go.mod:/app/go.mod
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: project231
  
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: project231
      ME_CONFIG_MONGODB_URL: mongodb://root:project231@mongo:27017/
